# Generated by Django 2.2 on 2019-05-07 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findmeal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findmeal.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findmeal.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findmeal.Recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='RecipeStepIngredient',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findmeal.RecipeStep'),
        ),
    ]
