# Generated by Django 2.2 on 2019-05-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmeal', '0002_auto_20190507_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='amount_required',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
