# Generated by Django 2.2 on 2019-05-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findmeal', '0003_recipeingredient_amount_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='amount_required',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='step',
        ),
    ]
