# Generated by Django 2.2 on 2019-05-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmeal', '0004_auto_20190511_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttype',
            name='description',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='1', upload_to='recipe'),
            preserve_default=False,
        ),
    ]
