# Generated by Django 2.2 on 2019-05-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmeal', '0006_auto_20190512_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='calories',
            new_name='calorie',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ratings',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='servings',
            new_name='serving',
        ),
        migrations.AddField(
            model_name='recipe',
            name='rateuser',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
