# Generated by Django 2.2 on 2019-05-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmeal', '0007_auto_20190514_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rateuser',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
