# Generated by Django 2.2 on 2019-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmeal', '0008_auto_20190516_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
    ]
