# Generated by Django 2.2 on 2019-05-31 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findmeal', '0011_recipe_prep_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='prep_times',
        ),
    ]
