# Generated by Django 2.2 on 2019-05-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmeal', '0012_remove_recipe_prep_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prepp_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
