# Generated by Django 2.2 on 2019-05-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findmeal', '0013_recipe_prepp_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='prepp_time',
        ),
    ]
