# Generated by Django 2.2 on 2019-05-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmeal', '0014_remove_recipe_prepp_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
