# Generated by Django 2.2.1 on 2019-09-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findmeal', '0022_auto_20190925_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ing', to='findmeal.Ingredient'),
        ),
    ]
